package com.example.hongzebin.schedule.greendao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.example.hongzebin.schedule.bean.Course;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "COURSE".
*/
public class CourseDao extends AbstractDao<Course, Long> {

    public static final String TABLENAME = "COURSE";

    /**
     * Properties of entity Course.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Name = new Property(1, String.class, "name", false, "NAME");
        public final static Property Number = new Property(2, String.class, "number", false, "NUMBER");
        public final static Property Major = new Property(3, String.class, "major", false, "MAJOR");
        public final static Property FigureNumber = new Property(4, String.class, "figureNumber", false, "FIGURENUMBER");
        public final static Property Time = new Property(5, String.class, "time", false, "TIME");
        public final static Property Week = new Property(6, String.class, "week", false, "WEEK");
        public final static Property Weekday = new Property(7, String.class, "weekday", false, "WEEKDAY");
        public final static Property Place = new Property(8, String.class, "place", false, "PLACE");
        public final static Property Teacher = new Property(9, String.class, "teacher", false, "TEACHER");
    }


    public CourseDao(DaoConfig config) {
        super(config);
    }
    
    public CourseDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"COURSE\" (" + //
                "\"_id\" INTEGER PRIMARY KEY ," + // 0: id
                "\"NAME\" TEXT," + // 1: name
                "\"NUMBER\" TEXT," + // 2: number
                "\"MAJOR\" TEXT," + // 3: major
                "\"FIGURENUMBER\" TEXT," + // 4: figureNumber
                "\"TIME\" TEXT," + // 5: time
                "\"WEEK\" TEXT," + // 6: week
                "\"WEEKDAY\" TEXT," + // 7: weekday
                "\"PLACE\" TEXT," + // 8: place
                "\"TEACHER\" TEXT);"); // 9: teacher
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"COURSE\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, Course entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(2, name);
        }
 
        String number = entity.getNumber();
        if (number != null) {
            stmt.bindString(3, number);
        }
 
        String major = entity.getMajor();
        if (major != null) {
            stmt.bindString(4, major);
        }
 
        String figureNumber = entity.getFigureNumber();
        if (figureNumber != null) {
            stmt.bindString(5, figureNumber);
        }
 
        String time = entity.getTime();
        if (time != null) {
            stmt.bindString(6, time);
        }
 
        String week = entity.getWeek();
        if (week != null) {
            stmt.bindString(7, week);
        }
 
        String weekday = entity.getWeekday();
        if (weekday != null) {
            stmt.bindString(8, weekday);
        }
 
        String place = entity.getPlace();
        if (place != null) {
            stmt.bindString(9, place);
        }
 
        String teacher = entity.getTeacher();
        if (teacher != null) {
            stmt.bindString(10, teacher);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, Course entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(2, name);
        }
 
        String number = entity.getNumber();
        if (number != null) {
            stmt.bindString(3, number);
        }
 
        String major = entity.getMajor();
        if (major != null) {
            stmt.bindString(4, major);
        }
 
        String figureNumber = entity.getFigureNumber();
        if (figureNumber != null) {
            stmt.bindString(5, figureNumber);
        }
 
        String time = entity.getTime();
        if (time != null) {
            stmt.bindString(6, time);
        }
 
        String week = entity.getWeek();
        if (week != null) {
            stmt.bindString(7, week);
        }
 
        String weekday = entity.getWeekday();
        if (weekday != null) {
            stmt.bindString(8, weekday);
        }
 
        String place = entity.getPlace();
        if (place != null) {
            stmt.bindString(9, place);
        }
 
        String teacher = entity.getTeacher();
        if (teacher != null) {
            stmt.bindString(10, teacher);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public Course readEntity(Cursor cursor, int offset) {
        Course entity = new Course( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // name
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // number
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // major
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // figureNumber
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // time
            cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6), // week
            cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7), // weekday
            cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8), // place
            cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9) // teacher
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, Course entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setName(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setNumber(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setMajor(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setFigureNumber(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setTime(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setWeek(cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6));
        entity.setWeekday(cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7));
        entity.setPlace(cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8));
        entity.setTeacher(cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(Course entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(Course entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(Course entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
